name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/workflows/deploy.yml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2

      - name: Installing Yarn.
        run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - name: Install dependencies and build website.
        run: yarn install && yarn build

      - name: Deploy to AWS.
        uses: lycuid/aws_deploy@master
        with:
          TARGET: ${{ format('{0}/{1}', github.workspace, 'public') }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          EC2_REMOTE_PATH: ${{ format('{0}/{1}', secrets.EC2_REMOTE_PATH, github.event.repository.name) }}
          S3_BUCKET_PATH: ${{ format('s3://{0}/p/{1}', secrets.S3_ASSETS_BUCKET, github.event.repository.name) }}
